# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T01:47:14+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class OperationType(Enum):
    OPERATION_TYPE_UNSPECIFIED = 'OPERATION_TYPE_UNSPECIFIED'
    EXPORT_ENTITIES = 'EXPORT_ENTITIES'
    IMPORT_ENTITIES = 'IMPORT_ENTITIES'
    CREATE_INDEX = 'CREATE_INDEX'
    DELETE_INDEX = 'DELETE_INDEX'


class State(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    INITIALIZING = 'INITIALIZING'
    PROCESSING = 'PROCESSING'
    CANCELLING = 'CANCELLING'
    FINALIZING = 'FINALIZING'
    SUCCESSFUL = 'SUCCESSFUL'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'


class GoogleDatastoreAdminV1CommonMetadata(BaseModel):
    endTime: Optional[str] = Field(
        None,
        description='The time the operation ended, either successfully or otherwise.',
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='The client-assigned labels which were provided when the operation was created. May also include additional labels.',
    )
    operationType: Optional[OperationType] = Field(
        None,
        description='The type of the operation. Can be used as a filter in ListOperationsRequest.',
    )
    startTime: Optional[str] = Field(
        None, description='The time that work began on the operation.'
    )
    state: Optional[State] = Field(
        None, description='The current state of the Operation.'
    )


class MigrationState(Enum):
    MIGRATION_STATE_UNSPECIFIED = 'MIGRATION_STATE_UNSPECIFIED'
    RUNNING = 'RUNNING'
    PAUSED = 'PAUSED'
    COMPLETE = 'COMPLETE'


class MigrationStep(Enum):
    MIGRATION_STEP_UNSPECIFIED = 'MIGRATION_STEP_UNSPECIFIED'
    PREPARE = 'PREPARE'
    START = 'START'
    APPLY_WRITES_SYNCHRONOUSLY = 'APPLY_WRITES_SYNCHRONOUSLY'
    COPY_AND_VERIFY = 'COPY_AND_VERIFY'
    REDIRECT_EVENTUALLY_CONSISTENT_READS = 'REDIRECT_EVENTUALLY_CONSISTENT_READS'
    REDIRECT_STRONGLY_CONSISTENT_READS = 'REDIRECT_STRONGLY_CONSISTENT_READS'
    REDIRECT_WRITES = 'REDIRECT_WRITES'


class GoogleDatastoreAdminV1DatastoreFirestoreMigrationMetadata(BaseModel):
    migrationState: Optional[MigrationState] = Field(
        None,
        description='The current state of migration from Cloud Datastore to Cloud Firestore in Datastore mode.',
    )
    migrationStep: Optional[MigrationStep] = Field(
        None,
        description='The current step of migration from Cloud Datastore to Cloud Firestore in Datastore mode.',
    )


class GoogleDatastoreAdminV1EntityFilter(BaseModel):
    kinds: Optional[List[str]] = Field(
        None, description='If empty, then this represents all kinds.'
    )
    namespaceIds: Optional[List[str]] = Field(
        None,
        description="An empty list represents all namespaces. This is the preferred usage for projects that don't use namespaces. An empty string element represents the default namespace. This should be used if the project has data in non-default namespaces, but doesn't want to include them. Each namespace in this list must be unique.",
    )


class GoogleDatastoreAdminV1ExportEntitiesResponse(BaseModel):
    outputUrl: Optional[str] = Field(
        None,
        description='Location of the output metadata file. This can be used to begin an import into Cloud Datastore (this project or another project). See google.datastore.admin.v1.ImportEntitiesRequest.input_url. Only present if the operation completed successfully.',
    )


class Step(Enum):
    MIGRATION_STEP_UNSPECIFIED = 'MIGRATION_STEP_UNSPECIFIED'
    PREPARE = 'PREPARE'
    START = 'START'
    APPLY_WRITES_SYNCHRONOUSLY = 'APPLY_WRITES_SYNCHRONOUSLY'
    COPY_AND_VERIFY = 'COPY_AND_VERIFY'
    REDIRECT_EVENTUALLY_CONSISTENT_READS = 'REDIRECT_EVENTUALLY_CONSISTENT_READS'
    REDIRECT_STRONGLY_CONSISTENT_READS = 'REDIRECT_STRONGLY_CONSISTENT_READS'
    REDIRECT_WRITES = 'REDIRECT_WRITES'


class State1(Enum):
    MIGRATION_STATE_UNSPECIFIED = 'MIGRATION_STATE_UNSPECIFIED'
    RUNNING = 'RUNNING'
    PAUSED = 'PAUSED'
    COMPLETE = 'COMPLETE'


class GoogleDatastoreAdminV1MigrationStateEvent(BaseModel):
    state: Optional[State1] = Field(None, description='The new state of the migration.')


class ConcurrencyMode(Enum):
    CONCURRENCY_MODE_UNSPECIFIED = 'CONCURRENCY_MODE_UNSPECIFIED'
    PESSIMISTIC = 'PESSIMISTIC'
    OPTIMISTIC = 'OPTIMISTIC'
    OPTIMISTIC_WITH_ENTITY_GROUPS = 'OPTIMISTIC_WITH_ENTITY_GROUPS'


class GoogleDatastoreAdminV1PrepareStepDetails(BaseModel):
    concurrencyMode: Optional[ConcurrencyMode] = Field(
        None,
        description='The concurrency mode this database will use when it reaches the `REDIRECT_WRITES` step.',
    )


class GoogleDatastoreAdminV1Progress(BaseModel):
    workCompleted: Optional[str] = Field(
        None,
        description='The amount of work that has been completed. Note that this may be greater than work_estimated.',
    )
    workEstimated: Optional[str] = Field(
        None,
        description='An estimate of how much work needs to be performed. May be zero if the work estimate is unavailable.',
    )


class GoogleDatastoreAdminV1RedirectWritesStepDetails(BaseModel):
    concurrencyMode: Optional[ConcurrencyMode] = Field(
        None, description='Ths concurrency mode for this database.'
    )


class OperationType1(Enum):
    OPERATION_TYPE_UNSPECIFIED = 'OPERATION_TYPE_UNSPECIFIED'
    EXPORT_ENTITIES = 'EXPORT_ENTITIES'
    IMPORT_ENTITIES = 'IMPORT_ENTITIES'


class State2(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    INITIALIZING = 'INITIALIZING'
    PROCESSING = 'PROCESSING'
    CANCELLING = 'CANCELLING'
    FINALIZING = 'FINALIZING'
    SUCCESSFUL = 'SUCCESSFUL'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'


class GoogleDatastoreAdminV1beta1CommonMetadata(BaseModel):
    endTime: Optional[str] = Field(
        None,
        description='The time the operation ended, either successfully or otherwise.',
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='The client-assigned labels which were provided when the operation was created. May also include additional labels.',
    )
    operationType: Optional[OperationType1] = Field(
        None,
        description='The type of the operation. Can be used as a filter in ListOperationsRequest.',
    )
    startTime: Optional[str] = Field(
        None, description='The time that work began on the operation.'
    )
    state: Optional[State2] = Field(
        None, description='The current state of the Operation.'
    )


class GoogleDatastoreAdminV1beta1EntityFilter(BaseModel):
    kinds: Optional[List[str]] = Field(
        None, description='If empty, then this represents all kinds.'
    )
    namespaceIds: Optional[List[str]] = Field(
        None,
        description="An empty list represents all namespaces. This is the preferred usage for projects that don't use namespaces. An empty string element represents the default namespace. This should be used if the project has data in non-default namespaces, but doesn't want to include them. Each namespace in this list must be unique.",
    )


class GoogleDatastoreAdminV1beta1ExportEntitiesRequest(BaseModel):
    entityFilter: Optional[GoogleDatastoreAdminV1beta1EntityFilter] = Field(
        None,
        description='Description of what data from the project is included in the export.',
    )
    labels: Optional[Dict[str, str]] = Field(
        None, description='Client-assigned labels.'
    )
    outputUrlPrefix: Optional[str] = Field(
        None,
        description='Location for the export metadata and data files. The full resource URL of the external storage location. Currently, only Google Cloud Storage is supported. So output_url_prefix should be of the form: `gs://BUCKET_NAME[/NAMESPACE_PATH]`, where `BUCKET_NAME` is the name of the Cloud Storage bucket and `NAMESPACE_PATH` is an optional Cloud Storage namespace path (this is not a Cloud Datastore namespace). For more information about Cloud Storage namespace paths, see [Object name considerations](https://cloud.google.com/storage/docs/naming#object-considerations). The resulting files will be nested deeper than the specified URL prefix. The final output URL will be provided in the google.datastore.admin.v1beta1.ExportEntitiesResponse.output_url field. That value should be used for subsequent ImportEntities operations. By nesting the data files deeper, the same Cloud Storage bucket can be used in multiple ExportEntities operations without conflict.',
    )


class GoogleDatastoreAdminV1beta1ExportEntitiesResponse(BaseModel):
    outputUrl: Optional[str] = Field(
        None,
        description='Location of the output metadata file. This can be used to begin an import into Cloud Datastore (this project or another project). See google.datastore.admin.v1beta1.ImportEntitiesRequest.input_url. Only present if the operation completed successfully.',
    )


class GoogleDatastoreAdminV1beta1ImportEntitiesRequest(BaseModel):
    entityFilter: Optional[GoogleDatastoreAdminV1beta1EntityFilter] = Field(
        None,
        description='Optionally specify which kinds/namespaces are to be imported. If provided, the list must be a subset of the EntityFilter used in creating the export, otherwise a FAILED_PRECONDITION error will be returned. If no filter is specified then all entities from the export are imported.',
    )
    inputUrl: Optional[str] = Field(
        None,
        description='The full resource URL of the external storage location. Currently, only Google Cloud Storage is supported. So input_url should be of the form: `gs://BUCKET_NAME[/NAMESPACE_PATH]/OVERALL_EXPORT_METADATA_FILE`, where `BUCKET_NAME` is the name of the Cloud Storage bucket, `NAMESPACE_PATH` is an optional Cloud Storage namespace path (this is not a Cloud Datastore namespace), and `OVERALL_EXPORT_METADATA_FILE` is the metadata file written by the ExportEntities operation. For more information about Cloud Storage namespace paths, see [Object name considerations](https://cloud.google.com/storage/docs/naming#object-considerations). For more information, see google.datastore.admin.v1beta1.ExportEntitiesResponse.output_url.',
    )
    labels: Optional[Dict[str, str]] = Field(
        None, description='Client-assigned labels.'
    )


class GoogleDatastoreAdminV1beta1Progress(BaseModel):
    workCompleted: Optional[str] = Field(
        None,
        description='The amount of work that has been completed. Note that this may be greater than work_estimated.',
    )
    workEstimated: Optional[str] = Field(
        None,
        description='An estimate of how much work needs to be performed. May be zero if the work estimate is unavailable.',
    )


class Status(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class GoogleDatastoreAdminV1ExportEntitiesMetadata(BaseModel):
    common: Optional[GoogleDatastoreAdminV1CommonMetadata] = Field(
        None, description='Metadata common to all Datastore Admin operations.'
    )
    entityFilter: Optional[GoogleDatastoreAdminV1EntityFilter] = Field(
        None, description='Description of which entities are being exported.'
    )
    outputUrlPrefix: Optional[str] = Field(
        None,
        description='Location for the export metadata and data files. This will be the same value as the google.datastore.admin.v1.ExportEntitiesRequest.output_url_prefix field. The final output location is provided in google.datastore.admin.v1.ExportEntitiesResponse.output_url.',
    )
    progressBytes: Optional[GoogleDatastoreAdminV1Progress] = Field(
        None, description='An estimate of the number of bytes processed.'
    )
    progressEntities: Optional[GoogleDatastoreAdminV1Progress] = Field(
        None, description='An estimate of the number of entities processed.'
    )


class GoogleDatastoreAdminV1ImportEntitiesMetadata(BaseModel):
    common: Optional[GoogleDatastoreAdminV1CommonMetadata] = Field(
        None, description='Metadata common to all Datastore Admin operations.'
    )
    entityFilter: Optional[GoogleDatastoreAdminV1EntityFilter] = Field(
        None, description='Description of which entities are being imported.'
    )
    inputUrl: Optional[str] = Field(
        None,
        description='The location of the import metadata file. This will be the same value as the google.datastore.admin.v1.ExportEntitiesResponse.output_url field.',
    )
    progressBytes: Optional[GoogleDatastoreAdminV1Progress] = Field(
        None, description='An estimate of the number of bytes processed.'
    )
    progressEntities: Optional[GoogleDatastoreAdminV1Progress] = Field(
        None, description='An estimate of the number of entities processed.'
    )


class GoogleDatastoreAdminV1IndexOperationMetadata(BaseModel):
    common: Optional[GoogleDatastoreAdminV1CommonMetadata] = Field(
        None, description='Metadata common to all Datastore Admin operations.'
    )
    indexId: Optional[str] = Field(
        None, description='The index resource ID that this operation is acting on.'
    )
    progressEntities: Optional[GoogleDatastoreAdminV1Progress] = Field(
        None, description='An estimate of the number of entities processed.'
    )


class GoogleDatastoreAdminV1MigrationProgressEvent(BaseModel):
    prepareStepDetails: Optional[GoogleDatastoreAdminV1PrepareStepDetails] = Field(
        None, description='Details for the `PREPARE` step.'
    )
    redirectWritesStepDetails: Optional[
        GoogleDatastoreAdminV1RedirectWritesStepDetails
    ] = Field(None, description='Details for the `REDIRECT_WRITES` step.')
    step: Optional[Step] = Field(
        None,
        description='The step that is starting. An event with step set to `START` indicates that the migration has been reverted back to the initial pre-migration state.',
    )


class GoogleDatastoreAdminV1beta1ExportEntitiesMetadata(BaseModel):
    common: Optional[GoogleDatastoreAdminV1beta1CommonMetadata] = Field(
        None, description='Metadata common to all Datastore Admin operations.'
    )
    entityFilter: Optional[GoogleDatastoreAdminV1beta1EntityFilter] = Field(
        None, description='Description of which entities are being exported.'
    )
    outputUrlPrefix: Optional[str] = Field(
        None,
        description='Location for the export metadata and data files. This will be the same value as the google.datastore.admin.v1beta1.ExportEntitiesRequest.output_url_prefix field. The final output location is provided in google.datastore.admin.v1beta1.ExportEntitiesResponse.output_url.',
    )
    progressBytes: Optional[GoogleDatastoreAdminV1beta1Progress] = Field(
        None, description='An estimate of the number of bytes processed.'
    )
    progressEntities: Optional[GoogleDatastoreAdminV1beta1Progress] = Field(
        None, description='An estimate of the number of entities processed.'
    )


class GoogleDatastoreAdminV1beta1ImportEntitiesMetadata(BaseModel):
    common: Optional[GoogleDatastoreAdminV1beta1CommonMetadata] = Field(
        None, description='Metadata common to all Datastore Admin operations.'
    )
    entityFilter: Optional[GoogleDatastoreAdminV1beta1EntityFilter] = Field(
        None, description='Description of which entities are being imported.'
    )
    inputUrl: Optional[str] = Field(
        None,
        description='The location of the import metadata file. This will be the same value as the google.datastore.admin.v1beta1.ExportEntitiesResponse.output_url field.',
    )
    progressBytes: Optional[GoogleDatastoreAdminV1beta1Progress] = Field(
        None, description='An estimate of the number of bytes processed.'
    )
    progressEntities: Optional[GoogleDatastoreAdminV1beta1Progress] = Field(
        None, description='An estimate of the number of entities processed.'
    )


class GoogleLongrunningOperation(BaseModel):
    done: Optional[bool] = Field(
        None,
        description='If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available.',
    )
    error: Optional[Status] = Field(
        None,
        description='The error result of the operation in case of failure or cancellation.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.',
    )
    name: Optional[str] = Field(
        None,
        description='The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should be a resource name ending with `operations/{unique_id}`.',
    )
    response: Optional[Dict[str, Any]] = Field(
        None,
        description='The normal response of the operation in case of success. If the original method returns no data on success, such as `Delete`, the response is `google.protobuf.Empty`. If the original method is standard `Get`/`Create`/`Update`, the response should be the resource. For other methods, the response should have the type `XxxResponse`, where `Xxx` is the original method name. For example, if the original method name is `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`.',
    )
